INSERT INTO Pais (CodigoIso2, CodigoIso3, Nombre, NombreOficial, Continente) VALUES
('AF', 'AFG', 'Afganistán', 'República Islámica de Afganistán', 'Asia'),
('AL', 'ALB', 'Albania', 'República de Albania', 'Europa'),
('DE', 'DEU', 'Alemania', 'República Federal de Alemania', 'Europa'),
('AD', 'AND', 'Andorra', 'Principado de Andorra', 'Europa'),
('AO', 'AGO', 'Angola', 'República de Angola', 'África'),
('AG', 'ATG', 'Antigua y Barbuda', 'Antigua y Barbuda', 'América'),
('SA', 'SAU', 'Arabia Saudita', 'Reino de Arabia Saudita', 'Asia'),
('DZ', 'DZA', 'Argelia', 'República Argelina Democrática y Popular', 'África'),
('AR', 'ARG', 'Argentina', 'República Argentina', 'América'),
('AM', 'ARM', 'Armenia', 'República de Armenia', 'Asia'),
('AU', 'AUS', 'Australia', 'Mancomunidad de Australia', 'Oceanía'),
('AT', 'AUT', 'Austria', 'República de Austria', 'Europa'),
('AZ', 'AZE', 'Azerbaiyán', 'República de Azerbaiyán', 'Asia'),

('BS', 'BHS', 'Bahamas', 'Mancomunidad de las Bahamas', 'América'),
('BH', 'BHR', 'Baréin', 'Reino de Baréin', 'Asia'),
('BD', 'BGD', 'Bangladés', 'República Popular de Bangladés', 'Asia'),
('BB', 'BRB', 'Barbados', 'Barbados', 'América'),
('BY', 'BLR', 'Bielorrusia', 'República de Belarús', 'Europa'),
('BE', 'BEL', 'Bélgica', 'Reino de Bélgica', 'Europa'),
('BZ', 'BLZ', 'Belice', 'Belice', 'América'),
('BJ', 'BEN', 'Benín', 'República de Benín', 'África'),
('BT', 'BTN', 'Bután', 'Reino de Bután', 'Asia'),
('BO', 'BOL', 'Bolivia', 'Estado Plurinacional de Bolivia', 'América'),
('BA', 'BIH', 'Bosnia y Herzegovina', 'Bosnia y Herzegovina', 'Europa'),
('BW', 'BWA', 'Botsuana', 'República de Botsuana', 'África'),
('BR', 'BRA', 'Brasil', 'República Federativa de Brasil', 'América'),
('BN', 'BRN', 'Brunéi', 'Nación del Brunéi, Morador de la Paz', 'Asia'),
('BG', 'BGR', 'Bulgaria', 'República de Bulgaria', 'Europa'),
('BF', 'BFA', 'Burkina Faso', 'Burkina Faso', 'África'),
('BI', 'BDI', 'Burundi', 'República de Burundi', 'África'),

('CV', 'CPV', 'Cabo Verde', 'República de Cabo Verde', 'África'),
('KH', 'KHM', 'Camboya', 'Reino de Camboya', 'Asia'),
('CM', 'CMR', 'Camerún', 'República de Camerún', 'África'),
('CA', 'CAN', 'Canadá', 'Canadá', 'América'),
('QA', 'QAT', 'Catar', 'Estado de Catar', 'Asia'),
('TD', 'TCD', 'Chad', 'República del Chad', 'África'),
('CL', 'CHL', 'Chile', 'República de Chile', 'América'),
('CN', 'CHN', 'China', 'República Popular China', 'Asia'),
('CY', 'CYP', 'Chipre', 'República de Chipre', 'Europa'),
('CO', 'COL', 'Colombia', 'República de Colombia', 'América'),
('KM', 'COM', 'Comoras', 'Unión de las Comoras', 'África'),
('CG', 'COG', 'Congo', 'República del Congo', 'África'),
('CD', 'COD', 'Congo (RD)', 'República Democrática del Congo', 'África'),
('KR', 'KOR', 'Corea del Sur', 'República de Corea', 'Asia'),
('KP', 'PRK', 'Corea del Norte', 'República Popular Democrática de Corea', 'Asia'),
('CR', 'CRI', 'Costa Rica', 'República de Costa Rica', 'América'),
('CI', 'CIV', 'Costa de Marfil', 'República de Côte d’Ivoire', 'África'),
('HR', 'HRV', 'Croacia', 'República de Croacia', 'Europa'),
('CU', 'CUB', 'Cuba', 'República de Cuba', 'América'),

('DK', 'DNK', 'Dinamarca', 'Reino de Dinamarca', 'Europa'),
('DM', 'DMA', 'Dominica', 'Mancomunidad de Dominica', 'América'),
('EC', 'ECU', 'Ecuador', 'República del Ecuador', 'América'),
('EG', 'EGY', 'Egipto', 'República Árabe de Egipto', 'África'),
('SV', 'SLV', 'El Salvador', 'República de El Salvador', 'América'),
('AE', 'ARE', 'Emiratos Árabes Unidos', 'Emiratos Árabes Unidos', 'Asia'),
('ER', 'ERI', 'Eritrea', 'Estado de Eritrea', 'África'),
('SK', 'SVK', 'Eslovaquia', 'República Eslovaca', 'Europa'),
('SI', 'SVN', 'Eslovenia', 'República de Eslovenia', 'Europa'),
('ES', 'ESP', 'España', 'Reino de España', 'Europa'),
('US', 'USA', 'Estados Unidos', 'Estados Unidos de América', 'América'),
('EE', 'EST', 'Estonia', 'República de Estonia', 'Europa'),
('ET', 'ETH', 'Etiopía', 'República Democrática Federal de Etiopía', 'África'),

('PH', 'PHL', 'Filipinas', 'República de Filipinas', 'Asia'),
('FI', 'FIN', 'Finlandia', 'República de Finlandia', 'Europa'),
('FR', 'FRA', 'Francia', 'República Francesa', 'Europa'),

('GA', 'GAB', 'Gabón', 'República Gabonesa', 'África'),
('GM', 'GMB', 'Gambia', 'República de Gambia', 'África'),
('GE', 'GEO', 'Georgia', 'Georgia', 'Asia'),
('GH', 'GHA', 'Ghana', 'República de Ghana', 'África'),
('GD', 'GRD', 'Granada', 'Granada', 'América'),
('GR', 'GRC', 'Grecia', 'República Helénica', 'Europa'),
('GT', 'GTM', 'Guatemala', 'República de Guatemala', 'América'),
('GN', 'GIN', 'Guinea', 'República de Guinea', 'África'),
('GQ', 'GNQ', 'Guinea Ecuatorial', 'República de Guinea Ecuatorial', 'África'),
('GW', 'GNB', 'Guinea-Bisáu', 'República de Guinea-Bisáu', 'África'),
('GY', 'GUY', 'Guyana', 'República Cooperativa de Guyana', 'América'),

('HT', 'HTI', 'Haití', 'República de Haití', 'América'),
('HN', 'HND', 'Honduras', 'República de Honduras', 'América'),
('HU', 'HUN', 'Hungría', 'Hungría', 'Europa'),

('IN', 'IND', 'India', 'República de la India', 'Asia'),
('ID', 'IDN', 'Indonesia', 'República de Indonesia', 'Asia'),
('IR', 'IRN', 'Irán', 'República Islámica de Irán', 'Asia'),
('IQ', 'IRQ', 'Irak', 'República de Irak', 'Asia'),
('IE', 'IRL', 'Irlanda', 'Irlanda', 'Europa'),
('IS', 'ISL', 'Islandia', 'República de Islandia', 'Europa'),
('IL', 'ISR', 'Israel', 'Estado de Israel', 'Asia'),
('IT', 'ITA', 'Italia', 'República Italiana', 'Europa'),

('JM', 'JAM', 'Jamaica', 'Jamaica', 'América'),
('JP', 'JPN', 'Japón', 'Estado de Japón', 'Asia'),
('JO', 'JOR', 'Jordania', 'Reino Hachemita de Jordania', 'Asia'),

('KZ', 'KAZ', 'Kazajistán', 'República de Kazajistán', 'Asia'),
('KE', 'KEN', 'Kenia', 'República de Kenia', 'África'),
('KG', 'KGZ', 'Kirguistán', 'República Kirguisa', 'Asia'),
('KI', 'KIR', 'Kiribati', 'República de Kiribati', 'Oceanía'),
('KW', 'KWT', 'Kuwait', 'Estado de Kuwait', 'Asia'),

('LA', 'LAO', 'Laos', 'República Democrática Popular Lao', 'Asia'),
('LS', 'LSO', 'Lesoto', 'Reino de Lesoto', 'África'),
('LV', 'LVA', 'Letonia', 'República de Letonia', 'Europa'),
('LB', 'LBN', 'Líbano', 'República Libanesa', 'Asia'),
('LR', 'LBR', 'Liberia', 'República de Liberia', 'África'),
('LY', 'LBY', 'Libia', 'Estado de Libia', 'África'),
('LI', 'LIE', 'Liechtenstein', 'Principado de Liechtenstein', 'Europa'),
('LT', 'LTU', 'Lituania', 'República de Lituania', 'Europa'),
('LU', 'LUX', 'Luxemburgo', 'Gran Ducado de Luxemburgo', 'Europa'),

('MK', 'MKD', 'Macedonia del Norte', 'República de Macedonia del Norte', 'Europa'),
('MG', 'MDG', 'Madagascar', 'República de Madagascar', 'África'),
('MW', 'MWI', 'Malaui', 'República de Malaui', 'África'),
('MY', 'MYS', 'Malasia', 'Malasia', 'Asia'),
('MV', 'MDV', 'Maldivas', 'República de Maldivas', 'Asia'),
('ML', 'MLI', 'Malí', 'República de Malí', 'África'),
('MT', 'MLT', 'Malta', 'República de Malta', 'Europa'),
('MA', 'MAR', 'Marruecos', 'Reino de Marruecos', 'África'),
('MH', 'MHL', 'Islas Marshall', 'República de las Islas Marshall', 'Oceanía'),
('MU', 'MUS', 'Mauricio', 'República de Mauricio', 'África'),
('MR', 'MRT', 'Mauritania', 'República Islámica de Mauritania', 'África'),
('MX', 'MEX', 'México', 'Estados Unidos Mexicanos', 'América'),
('FM', 'FSM', 'Micronesia', 'Estados Federados de Micronesia', 'Oceanía'),
('MD', 'MDA', 'Moldavia', 'República de Moldavia', 'Europa'),
('MC', 'MCO', 'Mónaco', 'Principado de Mónaco', 'Europa'),
('MN', 'MNG', 'Mongolia', 'Mongolia', 'Asia'),
('ME', 'MNE', 'Montenegro', 'Montenegro', 'Europa'),
('MZ', 'MOZ', 'Mozambique', 'República de Mozambique', 'África'),
('MM', 'MMR', 'Myanmar', 'República de la Unión de Myanmar', 'Asia'),

('NA', 'NAM', 'Namibia', 'República de Namibia', 'África'),
('NR', 'NRU', 'Nauru', 'República de Nauru', 'Oceanía'),
('NP', 'NPL', 'Nepal', 'República Federal Democrática de Nepal', 'Asia'),
('NI', 'NIC', 'Nicaragua', 'República de Nicaragua', 'América'),
('NE', 'NER', 'Níger', 'República del Níger', 'África'),
('NG', 'NGA', 'Nigeria', 'República Federal de Nigeria', 'África'),
('NO', 'NOR', 'Noruega', 'Reino de Noruega', 'Europa'),
('NZ', 'NZL', 'Nueva Zelanda', 'Nueva Zelanda', 'Oceanía'),

('OM', 'OMN', 'Omán', 'Sultanato de Omán', 'Asia'),

('NL', 'NLD', 'Países Bajos', 'Reino de los Países Bajos', 'Europa'),
('PK', 'PAK', 'Pakistán', 'República Islámica de Pakistán', 'Asia'),
('PW', 'PLW', 'Palaos', 'República de Palaos', 'Oceanía'),
('PA', 'PAN', 'Panamá', 'República de Panamá', 'América'),
('PG', 'PNG', 'Papúa Nueva Guinea', 'Estado Independiente de Papúa Nueva Guinea', 'Oceanía'),
('PY', 'PRY', 'Paraguay', 'República del Paraguay', 'América'),
('PE', 'PER', 'Perú', 'República del Perú', 'América'),
('PL', 'POL', 'Polonia', 'República de Polonia', 'Europa'),
('PT', 'PRT', 'Portugal', 'República Portuguesa', 'Europa'),

('GB', 'GBR', 'Reino Unido', 'Reino Unido de Gran Bretaña e Irlanda del Norte', 'Europa'),
('CF', 'CAF', 'República Centroafricana', 'República Centroafricana', 'África'),
('CZ', 'CZE', 'República Checa', 'Chequia', 'Europa'),
('DO', 'DOM', 'República Dominicana', 'República Dominicana', 'América'),
('RW', 'RWA', 'Ruanda', 'República de Ruanda', 'África'),
('RO', 'ROU', 'Rumanía', 'Rumanía', 'Europa'),
('RU', 'RUS', 'Rusia', 'Federación de Rusia', 'Europa'),

('WS', 'WSM', 'Samoa', 'Estado Independiente de Samoa', 'Oceanía'),
('KN', 'KNA', 'San Cristóbal y Nieves', 'Federación de San Cristóbal y Nieves', 'América'),
('SM', 'SMR', 'San Marino', 'República de San Marino', 'Europa'),
('VC', 'VCT', 'San Vicente y las Granadinas', 'San Vicente y las Granadinas', 'América'),
('LC', 'LCA', 'Santa Lucía', 'Santa Lucía', 'América'),
('ST', 'STP', 'Santo Tomé y Príncipe', 'República Democrática de Santo Tomé y Príncipe', 'África'),
('SN', 'SEN', 'Senegal', 'República de Senegal', 'África'),
('RS', 'SRB', 'Serbia', 'República de Serbia', 'Europa'),
('SC', 'SYC', 'Seychelles', 'República de Seychelles', 'África'),
('SL', 'SLE', 'Sierra Leona', 'República de Sierra Leona', 'África'),
('SG', 'SGP', 'Singapur', 'República de Singapur', 'Asia'),
('SY', 'SYR', 'Siria', 'República Árabe Siria', 'Asia'),
('SO', 'SOM', 'Somalia', 'República Federal de Somalia', 'África'),
('LK', 'LKA', 'Sri Lanka', 'República Democrática Socialista de Sri Lanka', 'Asia'),
('ZA', 'ZAF', 'Sudáfrica', 'República de Sudáfrica', 'África'),
('SD', 'SDN', 'Sudán', 'República del Sudán', 'África'),
('SS', 'SSD', 'Sudán del Sur', 'República de Sudán del Sur', 'África'),
('SE', 'SWE', 'Suecia', 'Reino de Suecia', 'Europa'),
('CH', 'CHE', 'Suiza', 'Confederación Suiza', 'Europa'),
('SR', 'SUR', 'Surinam', 'República de Surinam', 'América'),

('TH', 'THA', 'Tailandia', 'Reino de Tailandia', 'Asia'),
('TW', 'TWN', 'Taiwán', 'República de China (Taiwán)', 'Asia'),
('TZ', 'TZA', 'Tanzania', 'República Unida de Tanzania', 'África'),
('TJ', 'TJK', 'Tayikistán', 'República de Tayikistán', 'Asia'),
('TL', 'TLS', 'Timor Oriental', 'República Democrática de Timor-Leste', 'Asia'),
('TG', 'TGO', 'Togo', 'República Togolesa', 'África'),
('TO', 'TON', 'Tonga', 'Reino de Tonga', 'Oceanía'),
('TT', 'TTO', 'Trinidad y Tobago', 'República de Trinidad y Tobago', 'América'),
('TN', 'TUN', 'Túnez', 'República Tunecina', 'África'),
('TM', 'TKM', 'Turkmenistán', 'Turkmenistán', 'Asia'),
('TR', 'TUR', 'Turquía', 'República de Turquía', 'Asia'),

('UA', 'UKR', 'Ucrania', 'Ucrania', 'Europa'),
('UG', 'UGA', 'Uganda', 'República de Uganda', 'África'),
('UY', 'URY', 'Uruguay', 'República Oriental del Uruguay', 'América'),
('UZ', 'UZB', 'Uzbekistán', 'República de Uzbekistán', 'Asia'),

('VU', 'VUT', 'Vanuatu', 'República de Vanuatu', 'Oceanía'),
('VA', 'VAT', 'Vaticano', 'Ciudad del Vaticano', 'Europa'),
('VE', 'VEN', 'Venezuela', 'República Bolivariana de Venezuela', 'América'),
('VN', 'VNM', 'Vietnam', 'República Socialista de Vietnam', 'Asia'),

('YE', 'YEM', 'Yemen', 'República de Yemen', 'Asia'),

('ZM', 'ZMB', 'Zambia', 'República de Zambia', 'África'),
('ZW', 'ZWE', 'Zimbabue', 'República de Zimbabue', 'África');
